// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package server

import (
	"context"

	"pkg.aiocean.dev/polvoservice/internal/repository"
	"pkg.aiocean.dev/serviceutil/logger"
)

// Injectors from wire.go:

func initializeServer(ctx context.Context) (*Server, error) {
	zapLogger, err := logger.NewLogger(ctx)
	if err != nil {
		return nil, err
	}
	firestoreRepository, err := repository.NewFirestoreRepository()
	if err != nil {
		return nil, err
	}
	server := NewServer(zapLogger, firestoreRepository)
	return server, nil
}
